### ISSUE TITLE
tmle3optmttx exercise problem -- simplified rule 

### ISSUE THREAD

**Issue by jbriggs7** [tlverse/tlverse-handbook#18]
Hi, 

I am attempting to work through the exercise at the end of this chapter. While I can get a TMLE value of the optimal ITR, and also for the realistic optimal ITR, when I attempt to get the simplified rule xgboost appears to be throwing errors. 

#a simpler rule
tmle_spec2 <- tmle3_mopttx_blip_revere(
  V = c("momedu", "floor", "asset_refrig"), type = "blip2",
  learners = learner_list,
  maximize = TRUE, complex = FALSE, realistic = FALSE
)

fit <- tmle3(tmle_spec2, data = washb_data, node_list, learner_list)

**Error in xgboost::xgb.DMatrix(Xmat) : 
  xgb.DMatrix does not support construction from double
Error in if (nrow(Xmat) > 0) { : argument is of length zero
Failed on predict
Error in self$compute_step() : 
  Error in if (nrow(Xmat) > 0) { : argument is of length zero**

I can provide all of my code if that is helpful.

**Comment by podTockom** [comment]
Hi, 

this seems to be a xgboost error; if your library has other learners, you should still get a fit object.

**Comment by jbriggs7** [comment]
Yes that's true (didn't realize a fit object was still returned). Thanks, can be closed.

**Comment by podTockom** [comment]
No problem, thanks for pointing out!
