### ISSUE TITLE
Unrendered equation in chapter 4

### ISSUE THREAD

**Issue by ad1729** [tlverse/tlverse-handbook#30]
Hi, 

Thanks for this wonderful handbook! 

In chapter 4 (see link to line in the Rmd file below), the closing bracket for `\psi{}` is missing: 

https://github.com/tlverse/tlverse-handbook/blob/7001319f1004e26efbcdac3fefbfaaf1015cbc99/04-roadmap.Rmd#L575

Screenshot below of this link: https://tlverse.org/tlverse-handbook/roadmap.html#missingness

![image](https://user-images.githubusercontent.com/10787039/234267841-47d3b036-9929-40b9-896c-79994f6b4ffb.png)

**Comment by nhejazi** [comment]
Thank you for your kind words about our book, and we're glad you've found it to be a helpful resource. The typo you spotted has been addressed in #31, which should be merged soon; thanks for helping us catch this.

**Comment by ad1729** [comment]
Happy to have helped!
