### ISSUE TITLE
Refer to `create_github_token()` instead of `browse_github_pat()`

### ISSUE THREAD

**Issue by olivroy** [tlverse/tlverse-handbook#35]
https://github.com/tlverse/tlverse-handbook/blob/48a232a141cb676a405f784c3e1062f025513d2d/02-tlverse.Rmd#L268

**Comment by nhejazi** [comment]
thanks for flagging, we will change this soon

**Comment by nhejazi** [comment]
resolved in [2e33a1e](https://github.com/tlverse/tlverse-handbook/commit/2e33a1ea42639ccf62a59c4527547f2e6c3d2a8b)
